
import { Abbreviation, ConversionEntry, Technique, YarnWeight, YarnFiber } from './types';

// A tiny 1x1 transparent GIF base64 encoded for placeholder purposes
const BASE64_PLACEHOLDER_IMAGE = 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';

export const COMMON_ABBREVIATIONS: Abbreviation[] = [
  { us: 'ch', uk: 'ch', description: 'Chain' },
  { us: 'sc', uk: 'dc', description: 'Single Crochet (US) / Double Crochet (UK)' },
  { us: 'hdc', uk: 'htr', description: 'Half Double Crochet (US) / Half Treble Crochet (UK)' },
  { us: 'dc', uk: 'tr', description: 'Double Crochet (US) / Treble Crochet (UK)' },
  { us: 'tr', uk: 'dtr', description: 'Treble Crochet (US) / Double Treble Crochet (UK)' },
  { us: 'sl st', uk: 'sl st', description: 'Slip Stitch' },
  { us: 'st(s)', uk: 'st(s)', description: 'Stitch(es)' },
  { us: 'rnd(s)', uk: 'rnd(s)', description: 'Round(s)' },
  { us: 'row(s)', uk: 'row(s)', description: 'Row(s)' },
  { us: 'inc', uk: 'inc', description: 'Increase' },
  { us: 'dec', uk: 'dec', description: 'Decrease' },
  { us: 'sk', uk: 'sk', description: 'Skip' },
  { us: 'yo', uk: 'yrh', description: 'Yarn Over (US) / Yarn Round Hook (UK)' },
  { us: 'f/o', uk: 'f/o', description: 'Fasten Off' },
  { us: 'pm', uk: 'pm', description: 'Place Marker' },
  { us: 'lp(s)', uk: 'lp(s)', description: 'Loop(s)' },
];

export const US_UK_CONVERSION_CHART: ConversionEntry[] = [
  { us: 'Single Crochet (sc)', uk: 'Double Crochet (dc)', explanation: 'The US "single crochet" is equivalent to the UK "double crochet". This is one of the most common differences.' },
  { us: 'Half Double Crochet (hdc)', uk: 'Half Treble Crochet (htr)', explanation: 'The US "half double crochet" corresponds to the UK "half treble crochet".' },
  { us: 'Double Crochet (dc)', uk: 'Treble Crochet (tr)', explanation: 'The US "double crochet" is equivalent to the UK "treble crochet".' },
  { us: 'Treble Crochet (tr)', uk: 'Double Treble Crochet (dtr)', explanation: 'The US "treble crochet" is equivalent to the UK "double treble crochet".' },
  { us: 'Double Treble Crochet (dtr)', uk: 'Triple Treble Crochet (ttr)', explanation: 'The US "double treble crochet" is equivalent to the UK "triple treble crochet".' },
  { us: 'Slip Stitch (sl st)', uk: 'Slip Stitch (sl st)', explanation: 'This stitch has the same name and abbreviation in both US and UK terminology.' },
  { us: 'Chain (ch)', uk: 'Chain (ch)', explanation: 'This stitch has the same name and abbreviation in both US and UK terminology.' },
  { us: 'Yarn Over (yo)', uk: 'Yarn Round Hook (yrh)', explanation: 'The action of wrapping yarn around the hook is called "yarn over" in US and "yarn round hook" in UK terminology.' },
];

export const CROCHET_TECHNIQUES: Technique[] = [
  {
    id: 'slipknot',
    name: 'Slipknot',
    description: 'The slipknot is the very first step to starting any crochet project. It creates a loop on your hook that you can then work stitches into.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Make a loop with your yarn, ensuring the tail end is behind the working yarn.',
      'Insert your hook into the loop from front to back.',
      'Catch the working yarn with your hook.',
      'Pull the working yarn through the loop.',
      'Pull on both the working yarn and the tail to tighten the knot around your hook, but not too tightly that it can\'t move.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'starter-chain',
    name: 'Starter Chain (Chain Stitch)',
    description: 'The chain stitch forms the foundation row for most crochet projects. It\'s a series of interlocking loops.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Start with a slipknot on your hook.',
      'Yarn over (yo) your hook from back to front.',
      'Draw the yarn through the loop on your hook.',
      'This completes one chain stitch. Repeat steps 2 and 3 until you have the desired number of chains.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'slip-stitch',
    name: 'Slip Stitch (sl st)',
    description: 'The shortest of all crochet stitches. Used to join rounds, move yarn across stitches without adding height, or for decorative edging.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Insert your hook into the next stitch or space indicated.',
      'Yarn over (yo).',
      'Pull the yarn through both the stitch AND the loop on your hook in one smooth motion.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'magic-ring',
    name: 'Magic Ring (Magic Circle)',
    description: 'The magic ring creates a tight, adjustable center for working in the round, often used for amigurumi or hats.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Wrap the yarn around your fingers (usually index and middle) to form a loop, with the tail end crossing over the working yarn.',
      'Insert your hook under the first strand of yarn on your finger.',
      'Hook the working yarn and pull up a loop.',
      'Chain 1 to secure the loop (this chain does not count as a stitch).',
      'Work your first round of stitches (e.g., single crochets) into the ring, over both the loop and the tail.',
      'Once all stitches are made, pull the tail end to close the ring tightly.',
      'Join with a slip stitch to the first stitch of the round.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'single-crochet',
    name: 'Single Crochet (sc) - US Terminology',
    description: 'The single crochet is one of the most fundamental stitches, creating a dense and sturdy fabric.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Insert hook into the desired stitch (usually the second chain from the hook for a foundation row).',
      'Yarn over (yo).',
      'Pull yarn through the stitch (you now have 2 loops on your hook).',
      'Yarn over (yo) again.',
      'Pull yarn through both loops on your hook. One single crochet stitch is complete.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'double-crochet',
    name: 'Double Crochet (dc) - US Terminology',
    description: 'The double crochet is taller than a single crochet, producing a looser fabric with more drape.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Yarn over (yo).',
      'Insert hook into the desired stitch (usually the fourth chain from the hook for a foundation row for dc).',
      'Yarn over (yo) and pull yarn through the stitch (you now have 3 loops on your hook).',
      'Yarn over (yo) and pull yarn through the first two loops on your hook (you now have 2 loops on your hook).',
      'Yarn over (yo) again and pull yarn through the remaining two loops on your hook. One double crochet stitch is complete.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'half-double-crochet',
    name: 'Half Double Crochet (hdc) - US Terminology',
    description: 'The half double crochet is a stitch that falls between the single crochet and double crochet in height, offering a balanced fabric.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Yarn over (yo).',
      'Insert hook into the desired stitch (usually the third chain from the hook for a foundation row).',
      'Yarn over (yo) and pull yarn through the stitch (you now have 3 loops on your hook).',
      'Yarn over (yo) and pull yarn through all three loops on your hook. One half double crochet stitch is complete.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'treble-crochet',
    name: 'Treble Crochet (tr) - US Terminology',
    description: 'The treble crochet is a tall stitch that creates a very open and lacy fabric, often used for decorative purposes or quick projects.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Yarn over (yo) twice.',
      'Insert hook into the desired stitch (usually the fifth chain from the hook for a foundation row).',
      'Yarn over (yo) and pull yarn through the stitch (you now have 4 loops on your hook).',
      'Yarn over (yo) and pull yarn through the first two loops on your hook (3 loops remain).',
      'Yarn over (yo) and pull yarn through the next two loops on your hook (2 loops remain).',
      'Yarn over (yo) again and pull yarn through the final two loops on your hook. One treble crochet stitch is complete.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'front-post-double-crochet',
    name: 'Front Post Double Crochet (FPDC)',
    description: 'The Front Post Double Crochet creates a raised, textured stitch often used for ribbing or cables.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Yarn over (yo).',
      'Insert your hook from front to back, then back to front around the post of the specified stitch in the previous row.',
      'Yarn over (yo) and pull up a loop (3 loops on hook).',
      'Yarn over (yo) and draw through 2 loops (2 loops on hook).',
      'Yarn over (yo) and draw through the remaining 2 loops. FPDC complete.',
    ],
    difficulty: 'Intermediate',
  },
  {
    id: 'back-post-double-crochet',
    name: 'Back Post Double Crochet (BPDC)',
    description: 'The Back Post Double Crochet creates a recessed, textured stitch, often paired with FPDC for ribbing.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Yarn over (yo).',
      'Insert your hook from back to front, then front to back around the post of the specified stitch in the previous row.',
      'Yarn over (yo) and pull up a loop (3 loops on hook).',
      'Yarn over (yo) and draw through 2 loops (2 loops on hook).',
      'Yarn over (yo) and draw through the remaining 2 loops. BPDC complete.',
    ],
    difficulty: 'Intermediate',
  },
  {
    id: 'crochet-in-the-round',
    name: 'Crocheting in the Round',
    description: 'Technique for creating circular or tubular items, often starting with a magic ring or chain loop.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Start with a magic ring or by chaining a few stitches and joining with a slip stitch to form a ring.',
      'Work the first round of stitches into the center of the ring or chain loop.',
      'Join the end of the round to the first stitch with a slip stitch (if not working in continuous spirals).',
      'Chain up to the appropriate height for the next round (e.g., ch 1 for sc, ch 2 for hdc, ch 3 for dc).',
      'Continue working stitches, increasing as needed to keep the work flat or shape it as desired.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'joining-new-yarn',
    name: 'Joining New Yarn',
    description: 'How to seamlessly add a new ball of yarn or change colors in your crochet project.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Work until you have two loops left on your hook from the last stitch of the old yarn.',
      'Drop the old yarn.',
      'Pick up the new yarn and yarn over (yo) with the new yarn.',
      'Pull the new yarn through both loops on your hook to complete the stitch.',
      'Secure the ends by weaving them in later or tying a small knot close to the work.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 'corner-to-corner',
    name: 'Corner to Corner (C2C)',
    description: 'A technique used to create pixel-art style blankets and graphs, working diagonally from one corner to the opposite corner using blocks of double crochet.',
    imageUrl: BASE64_PLACEHOLDER_IMAGE,
    hasVideoTutorial: true,
    steps: [
      'Row 1 (Block 1): Chain 6. DC in 4th chain from hook and next 2 chains.',
      'Row 2 (Increase): Turn work. Chain 6. DC in 4th chain from hook and next 2 chains. Slip stitch into the ch-3 space of the first block. Chain 3, 3 DC into same ch-3 space.',
      'Row 3+: Continue increasing by making a new block at start of row (Ch 6, DC in 4th ch & next 2), then sl st to previous row blocks, Ch 3, 3 DC in ch-space across.',
      'Decrease: Instead of chaining 6 at start, slip stitch across the last 3 DC to the ch-space, then build blocks as normal to square off the project.',
    ],
    difficulty: 'Intermediate',
  },
];

export const YARN_WEIGHTS: YarnWeight[] = [
  {
    category: '0',
    name: 'Lace',
    gaugeRange: '33-40 stitches per 4 inches',
    hookSize: 'Steel hook 6, 7, 8 (1.75-2.25 mm) or B-1 (2.25 mm)',
    description: 'Also known as cobweb or thread, this is the finest yarn available. It creates delicate, airy fabrics.',
    exampleProjects: ['Lace shawls', 'Fine garments', 'Doylies'],
  },
  {
    category: '1',
    name: 'Super Fine',
    gaugeRange: '27-32 stitches per 4 inches',
    hookSize: 'B-1 to E-4 (2.25-3.5 mm)',
    description: 'Fingering, sock, or baby weight. This lightweight yarn is perfect for intricate patterns and warm, yet thin, items.',
    exampleProjects: ['Socks', 'Baby clothes', 'Lightweight scarves'],
  },
  {
    category: '2',
    name: 'Fine',
    gaugeRange: '23-26 stitches per 4 inches',
    hookSize: 'E-4 to 7 (3.5-4.5 mm)',
    description: 'Sport or baby weight. A slightly heavier yarn than super fine, good for garments and accessories that need a bit more substance.',
    exampleProjects: ['Sport-weight garments', 'Baby blankets', 'Shawls'],
  },
  {
    category: '3',
    name: 'Light',
    gaugeRange: '21-24 stitches per 4 inches',
    hookSize: '7 to I-9 (4.5-5.5 mm)',
    description: 'DK (double knitting) or light worsted. This is a versatile, medium-light yarn suitable for a wide range of projects.',
    exampleProjects: ['Sweaters', 'Cardigans', 'Hats', 'Blankets'],
  },
  {
    category: '4',
    name: 'Medium',
    gaugeRange: '16-20 stitches per 4 inches',
    hookSize: 'I-9 to K-10.5 (5.5-6.5 mm)',
    description: 'Worsted, afghan, or aran weight. This is the most common and widely used yarn weight, easy to work with and creates a well-defined stitch.',
    exampleProjects: ['Afghans', 'Sweaters', 'Scarves', 'Hats', 'Amigurumi'],
  },
  {
    category: '5',
    name: 'Bulky',
    gaugeRange: '12-15 stitches per 4 inches',
    hookSize: 'K-10.5 to M-13 (6.5-9 mm)',
    description: 'Chunky, craft, or bulky. This yarn works up quickly, creating thick and warm items.',
    exampleProjects: ['Chunky blankets', 'Warm scarves', 'Beanies', 'Cozy sweaters'],
  },
  {
    category: '6',
    name: 'Super Bulky',
    gaugeRange: '7-11 stitches per 4 inches',
    hookSize: 'M-13 to P-16 (9-12 mm)',
    description: 'Roving or super bulky. Even thicker than bulky, perfect for very quick projects and extremely warm accessories.',
    exampleProjects: ['Quick blankets', 'Thick cowls', 'Large scarves'],
  },
  {
    category: '7',
    name: 'Jumbo',
    gaugeRange: '0-6 stitches per 4 inches',
    hookSize: '15 mm and larger',
    description: 'This is the thickest yarn, often used for arm knitting or with very large hooks to create oversized, statement pieces.',
    exampleProjects: ['Giant blankets', 'Chunky poufs', 'Statement home decor'],
  },
];

export const YARN_FIBERS: YarnFiber[] = [
  {
    id: 'acrylic',
    name: 'Acrylic',
    description: 'A synthetic fiber that is affordable, widely available, and comes in a massive variety of colors.',
    properties: ['Durable', 'Machine washable', 'Hypoallergenic', 'Inexpensive', 'Can pill over time'],
    careInstructions: 'Usually machine wash and dry.'
  },
  {
    id: 'cotton',
    name: 'Cotton',
    description: 'A natural plant fiber that is inelastic but strong and breathable.',
    properties: ['Breathable', 'Durable', 'Inelastic (holds shape)', 'Absorbent', 'Heat resistant'],
    careInstructions: 'Machine wash, may shrink if dried in high heat.'
  },
  {
    id: 'wool',
    name: 'Wool',
    description: 'A natural animal fiber (usually sheep) known for warmth and elasticity.',
    properties: ['Warm', 'Elastic/Springy', 'Breathable', 'Fire resistant', 'Can felt if agitated'],
    careInstructions: 'Hand wash in cool water and lay flat to dry (unless superwash).'
  },
  {
    id: 'alpaca',
    name: 'Alpaca',
    description: 'A natural fiber from alpacas, warmer and softer than sheep\'s wool, and contains no lanolin.',
    properties: ['Very soft', 'Warmer than wool', 'Hypoallergenic', 'Drapes well', 'Less elastic than wool'],
    careInstructions: 'Gentle hand wash, lay flat to dry.'
  },
  {
    id: 'bamboo',
    name: 'Bamboo',
    description: 'A semi-synthetic fiber derived from bamboo pulp, usually processed into viscose.',
    properties: ['Silky soft', 'Beautiful drape', 'Antibacterial', 'Breathable', 'Can split easily'],
    careInstructions: 'Gentle wash, often best to hand wash.'
  },
  {
    id: 'blend',
    name: 'Blends (e.g., Wool/Acrylic)',
    description: 'Combinations of different fibers to maximize the benefits of each.',
    properties: ['Versatile', 'Balances cost and quality', 'Varying properties based on mix'],
    careInstructions: 'Check label; usually follows the most delicate fiber in the blend.'
  },
  {
    id: 'polyester',
    name: 'Polyester',
    description: 'A synthetic fiber often used for novelty yarns like scrubbing yarn or faux fur.',
    properties: ['Strong', 'Resistant to stretching', 'Quick drying', 'Not breathable'],
    careInstructions: 'Machine washable.'
  },
];

export const CROCHET_HOOK_SIZES = [
  '2.0 mm',
  '2.25 mm (B-1)',
  '2.5 mm',
  '2.75 mm (C-2)',
  '3.0 mm',
  '3.25 mm (D-3)',
  '3.5 mm (E-4)',
  '3.75 mm (F-5)',
  '4.0 mm (G-6)',
  '4.25 mm (G)',
  '4.5 mm (7)',
  '5.0 mm (H-8)',
  '5.25 mm (I)',
  '5.5 mm (I-9)',
  '5.75 mm (J)',
  '6.0 mm (J-10)',
  '6.5 mm (K-10.5)',
  '7.0 mm',
  '8.0 mm (L-11)',
  '9.0 mm (M/N-13)',
  '10.0 mm (N/P-15)',
  '12.0 mm',
  '15.0 mm (P/Q)',
  '16.0 mm (Q)',
  '19.0 mm (S)',
  '25.0 mm (U)'
];
